;==========================================================
;  wiredWM / X11 Polybar
;  nightshadeNeon-Glitch
;
;  X11 counterpart to wiredWM's Waybar configuration
;  - by rav3ndust
;==========================================================

[colors]
background = #E60A0A0A
foreground = #00FFFF

primary = #FF10F0
secondary = #39FF14
cyan = #00FFFF
alert = #FF3131

disabled = #505050
border = #800080

;----------------------------------------------------------
; BAR
;----------------------------------------------------------

[bar/main]
width = 100%
height = 18pt

fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 2pt
border-color = ${colors.border}

border-top-size = 0
border-bottom-size = 2pt
border-bottom-color = ${colors.primary}

line-size = 2pt
line-color = ${colors.primary}

padding-left = 2
padding-right = 2
padding-top = 1
padding-bottom = 1

module-margin = 0.7

separator = " | "
separator-foreground = ${colors.disabled}

font-0 = Noto Sans:style=Bold:size=10;2
font-1 = MaterialDesignIcons-Regular:size=10;2
font-2 = FontAwesome:size=10;2
font-3 = Unifont:size=10;2

wm-restack = i3
enable-ipc = true
override-redirect = false

tray-position = right
tray-spacing = 6px
tray-padding = 4px

modules-left = wired-launcher xworkspaces xwindow
modules-center = date-1 date-2 date-3
modules-right = pulseaudio network battery tray custom/power

;==========================================================
; MODULES
;==========================================================

;----------------------------------------------------------
; WIRED LAUNCHER
;----------------------------------------------------------

[module/wired-launcher]
type = custom/text

format = <label>

label = %{A1:rofi -show combi -modi window,drun,run:}∅%{A}
label-font = 3 
label-foreground = ${colors.primary}
label-background = ${colors.background}
label-padding = 2

;----------------------------------------------------------
; WORKSPACES
;----------------------------------------------------------

[module/xworkspaces]
type = internal/xworkspaces

format = <label-state>

label-active = %name%
label-active-foreground = ${colors.primary}
label-active-background = ${colors.background}
label-active-underline = ${colors.secondary}
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = ${colors.cyan}
label-occupied-background = ${colors.background}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.background}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-background = ${colors.background}
label-empty-padding = 1

;----------------------------------------------------------
; ACTIVE WINDOW
;----------------------------------------------------------

[module/xwindow]
type = internal/xwindow

label = %title:0:60:...%
label-foreground = ${colors.alert}
label-background = ${colors.background}
label-padding = 2

;----------------------------------------------------------
; DAY
;----------------------------------------------------------

[module/date-1]
type = internal/date
interval = 1

date = %A

label = %{A1:st -e calcurse &:}%date%%{A}
label-foreground = ${colors.secondary}
label-background = ${colors.background}
label-padding = 2

;----------------------------------------------------------
; TIME
;----------------------------------------------------------

[module/date-2]
type = internal/date
interval = 1

date = %H:%M

label = %{A1:st -e tty-clock &:}%date%%{A}
label-foreground = ${colors.secondary}
label-background = ${colors.background}
label-padding = 2

;----------------------------------------------------------
; DATE
;----------------------------------------------------------

[module/date-3]
type = internal/date
interval = 1

date = %d %B

label = %{A1:gsimplecal &:}%date%%{A}
label-foreground = ${colors.secondary}
label-background = ${colors.background}
label-padding = 2

;----------------------------------------------------------
; AUDIO
;----------------------------------------------------------

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}

label-volume = %percentage%%
label-volume-foreground = ${colors.primary}
label-volume-padding = 2

format-muted = <label-muted>
format-muted-prefix = " "
format-muted-prefix-foreground = ${colors.disabled}

label-muted = mute
label-muted-foreground = ${colors.disabled}
label-muted-padding = 2

click-left = pamixer -t
click-right = pavucontrol

;----------------------------------------------------------
; NETWORK
;----------------------------------------------------------

[module/network]
type = internal/network

interface-type = wireless
interval = 5

format-connected = <label-connected>
format-disconnected = <label-disconnected>

;label-connected = %{A1:st -e nmtui &:} %signal%%%{A}
label-connected = %{A1:alacritty -e navi-networks &:} %signal%%%{A}
;XXX testing out `navi-networks` from naviMods.
label-connected-foreground = ${colors.primary}
label-connected-background = ${colors.background}
label-connected-padding = 2

;label-disconnected = %{A1:st -e nmtui &:}%{A}
label-disconnected = %{A1:alacritty -e navi-networks &:}%{A}
; XXX testing out `navi-networks` from naviMods. 
label-disconnected-foreground = ${colors.alert}
label-disconnected-background = ${colors.background}
label-disconnected-padding = 2

click-left = alacritty -e navi-networks &
;----------------------------------------------------------
; BATTERY
;----------------------------------------------------------

[module/battery]
type = internal/battery

battery = BAT0
adapter = ADP1

full-at = 99
low-at = 15
poll-interval = 5

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>

label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = "%percentage%% "

label-charging-foreground = ${colors.primary}
label-discharging-foreground = ${colors.primary}
label-full-foreground = ${colors.primary}

label-charging-background = ${colors.background}
label-discharging-background = ${colors.background}
label-full-background = ${colors.background}

label-charging-padding = 2
label-discharging-padding = 2
label-full-padding = 2

;----------------------------------------------------------
; SYSTEM TRAY
;----------------------------------------------------------

[module/tray]
type = internal/tray

format = <tray>

tray-spacing = 6px
format-margin = 4px

;----------------------------------------------------------
; POWER MENU
;----------------------------------------------------------

[module/custom/power]
type = custom/text

label = %{A1:/usr/bin/power_menu:}%{A}
label-foreground = ${colors.primary}
label-background = ${colors.background}
label-padding = 2

;==========================================================
; SETTINGS
;==========================================================

[settings]
screenchange-reload = true
pseudo-transparency = false
