backend = "glx";
blur: {
  method = "kernel";
  strength = 9;
  background = false;
  background-frame = false;
  background-fixed = false;
}
opacity-rule = [
    "90:class_g = 'i3bar' && window_type = 'dock'"
];
blur-background-exclude = [
    "! class_g = 'i3bar'"

];
